<?php

namespace DEV\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByNotPublished(){
        return $this->createQueryBuilder('p')
            ->where('p.publishedAt IS  NULL')//avec null c'est ok aussi
            ->getQuery()
            ->getResult();
    }
}
